spring:
  profiles:
    active: local
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: govlepel@$&

#  jpa:
#    showSql: true
#    hibernate:
#      ddl-auto: create
#
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
