spring:
  jpa:
    showSql: true
    hibernate:
      ddl-auto: create
#  messages:
#    basename: i18n/exception
#    encoding: UTF-8
  jwt:
    secret: govlepel@$&

  h2:
    console:
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
